language: java
services:
- postgresql
before_script:
- psql -c 'create database dyfi_wildlife_centre;' -U postgres
env:
  global:
    secure: g5z2On8DyHxGZ3apD8CDpoUqmDXZQBK6OZLSG1vWBNtDluy/PqeFfqhKDhKwZY1fngOb9N6iT484eev7jGSJNoptZL6orxKoVyOat5UC7FBZUmO0LxGv5u0TeJfPgYMF8G+ikQBMgrPlvRJT98D3T6HA5mZKsslG+odaXSzYT6vK/j+S5/yikFfbjL9565RTksx4FsF7LnZH8mv3nxlc2rNhgxLdi+rXpR7cOI/3ayUN3CN3//0vZDt2e2P2GUOJ23o6tXkt176f9h+g+fPjkW4oNqj3XEBB8Wd1UG1UJKelaVmlg0+aTdpGR39ICSIgsS/gJRyDqR06PIHiPYPtqrzPJVr+Jm/8Px2xBNcPZ+g9NpLjnjgFwhaWUFc+RB78evkVFd+uNh6D8mXyP0UFZ0LYaJhtDyyAyBuaU8k/AEThugXT8WkDcjpG8DsL+/Db3msjm7VaMY2UYbYFsMlvjzv3SmWwccYfvIJ9QeJOLGxjbQbSQ/jzEQ1qSteiV+IZKzvnLq9ezrAaBAIgNQ0/pJiOwlu8pKB8Tt1Q3ba/Q2BHmwwyJuBp0/C5hctZ6UzT+jSE8V9wWwEpL7fxYRFBSXZwypvMrUr6BzinQno0GRgOCBvBdBq3ItfYIhWuZCod6awVkQQp0MTRnGgLwa+7Y3YSOJe58EaeQsnoqvmSOxs=
